// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8-1iKsxSQUAIqWfHXkzDFVVrfNP5cHSI',
    appId: '1:210297441335:web:c19847dd1f8ba0e2a343b2',
    messagingSenderId: '210297441335',
    projectId: 'wellpath-fitness',
    authDomain: 'wellpath-fitness.firebaseapp.com',
    storageBucket: 'wellpath-fitness.firebasestorage.app',
    measurementId: 'G-5CSMH0GCQ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRQbBOmMQiTkuvlDWcuiVe6OqrlsC4Wf8',
    appId: '1:210297441335:android:4a6986e80c0f0494a343b2',
    messagingSenderId: '210297441335',
    projectId: 'wellpath-fitness',
    storageBucket: 'wellpath-fitness.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6hfja9m6lh3zvRwEDzaXGlVOJ_4jbRWE',
    appId: '1:210297441335:ios:4b52f35bbefda4cba343b2',
    messagingSenderId: '210297441335',
    projectId: 'wellpath-fitness',
    storageBucket: 'wellpath-fitness.firebasestorage.app',
    iosBundleId: 'com.wellpath.wellpath',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6hfja9m6lh3zvRwEDzaXGlVOJ_4jbRWE',
    appId: '1:210297441335:ios:4b52f35bbefda4cba343b2',
    messagingSenderId: '210297441335',
    projectId: 'wellpath-fitness',
    storageBucket: 'wellpath-fitness.firebasestorage.app',
    iosBundleId: 'com.wellpath.wellpath',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8-1iKsxSQUAIqWfHXkzDFVVrfNP5cHSI',
    appId: '1:210297441335:web:55d3b2fef0cedc14a343b2',
    messagingSenderId: '210297441335',
    projectId: 'wellpath-fitness',
    authDomain: 'wellpath-fitness.firebaseapp.com',
    storageBucket: 'wellpath-fitness.firebasestorage.app',
    measurementId: 'G-VN4RSWXWHW',
  );
}
